apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
        env: dev
    spec:
      containers:
      - name: python
        image: acrloki.azurecr.io/k8sdemo
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi       
        ports:
        - name:  http
          containerPort: 8080
          protocol: TCP
