name: Build and Deploy to dev and staging
on:
  push:
    tags:
      - '*'
#     branches:
#       - main
 
env:
  REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      # Builds and pushes an image up to your Azure Container Registry
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - uses: tenhaus/get-release-or-tag@v2
#         id: tag

      - name: Get tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.1
        
      - name: Build and push image to ACR
        run: |
           az acr build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.REPOSITORY }}:${{.Run.ID}} -r ${{ secrets.AZURE_CONTAINER_REGISTRY }} .

 # Deployment to Dev
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: tenhaus/get-release-or-tag@v2
        id: tag
        
      - uses: Azure/aks-set-context@v1
        with:
           creds: '${{ secrets.AZURE_CREDENTIALS }}'
           cluster-name: '${{ secrets.cluster_name_dev }}'
           resource-group: '${{ secrets.resource_group }}' 
      
      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.ACR_LOGIN_SERVER }}
          container-registry-username: ${{ secrets.ACR_USERNAME }}
          container-registry-password: ${{ secrets.ACR_PASSWORD }}
          secret-name: k8s-secret

      - uses: Azure/k8s-deploy@v4
        with:
          manifests: |
            manifests/deployment.yaml
            manifests/service.yaml
          images: |
            ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.repository }}:${{.Run.ID}}
          imagepullsecrets: |
           k8s-secret

# Deployment to Staging
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: tenhaus/get-release-or-tag@v2
        id: tag
        
      - uses: Azure/aks-set-context@v1
        with:
           creds: '${{ secrets.AZURE_CREDENTIALS }}'
           cluster-name: '${{ secrets.cluster_name_dev }}'
           resource-group: '${{ secrets.resource_group }}' 
      
      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.ACR_LOGIN_SERVER }}
          container-registry-username: ${{ secrets.ACR_USERNAME }}
          container-registry-password: ${{ secrets.ACR_PASSWORD }}
          secret-name: k8s-secret

      - uses: Azure/k8s-deploy@v4
        with:
          manifests: |
            manifests/deployment.yaml
            manifests/service.yaml
          images: |
            ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.repository }}:${{.Run.ID}}
          imagepullsecrets: |
           k8s-secret
