name: Build and Deploy
on:
  push:
    tags:
      - '*'
 
env:
  REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            
      - name: Build and push image to ACR
        run: |
           az acr build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.REPOSITORY }}:${steps.meta.outputs.tags} -r ${{ secrets.AZURE_CONTAINER_REGISTRY }} .

 # Deployment to Dev
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
      - uses: Azure/aks-set-context@v1
        with:
           creds: '${{ secrets.AZURE_CREDENTIALS }}'
           cluster-name: '${{ secrets.cluster_name_dev }}'
           resource-group: '${{ secrets.resource_group }}' 
      
      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.ACR_LOGIN_SERVER }}
          container-registry-username: ${{ secrets.ACR_USERNAME }}
          container-registry-password: ${{ secrets.ACR_PASSWORD }}
          secret-name: k8s-secret

      - uses: Azure/k8s-deploy@v4
        with:
          manifests: |
            manifests/deployment.yaml
            manifests/service.yaml
          images: |
            ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.repository }}:${steps.meta.outputs.tags}
          imagepullsecrets: |
           k8s-secret

# Deployment to Staging
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
      - uses: Azure/aks-set-context@v1
        with:
           creds: '${{ secrets.AZURE_CREDENTIALS }}'
           cluster-name: '${{ secrets.cluster_name_dev }}'
           resource-group: '${{ secrets.resource_group }}' 
      
      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.ACR_LOGIN_SERVER }}
          container-registry-username: ${{ secrets.ACR_USERNAME }}
          container-registry-password: ${{ secrets.ACR_PASSWORD }}
          secret-name: k8s-secret

      - uses: Azure/k8s-deploy@v4
        with:
          manifests: |
            manifests/deployment.yaml
            manifests/service.yaml
          images: |
            ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.repository }}:${steps.meta.outputs.tags}
          imagepullsecrets: |
           k8s-secret
