name: Build and Deploy
on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'staging'
    tags:
      - '*'
  release:
    types:
      - 'created'

env:
  REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_NAME: my-python-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      # Builds and pushes an image up to your Azure Container Registry
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Build and push image to ACR
        run: |
           az acr build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.REPOSITORY }}:${{ github.sha }} -r ${{ secrets.AZURE_CONTAINER_REGISTRY }} .

  deploy:

   runs-on: ubuntu-latest
   needs: build
   steps:
    - uses: actions/checkout@v2
    
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: '${{ secrets.cluster_name }}'
        resource-group: '${{ secrets.resource_group }}' 
      
    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: ${{ secrets.ACR_LOGIN_SERVER }}
        container-registry-username: ${{ secrets.ACR_USERNAME }}
        container-registry-password: ${{ secrets.ACR_PASSWORD }}
        secret-name: k8s-secret

    - uses: Azure/k8s-deploy@v4
      with:
        manifests: |
          manifests/deployment.yaml
          manifests/service.yaml
        images: |
          ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.repository }}:${{ github.sha }}
        imagepullsecrets: |
            k8s-secret
